### ISSUE TITLE
Create the necessary components to run & deploy the webhook with OSM

### ISSUE THREAD

**Issue by steeling** [steeling/osm#2]
- [x] Add a dockerfile
- [x] Add a skeleton go binary (hello world is fine)
- [x] Add to the makefile
- [x] Add to the helm charts
- [ ] Fix up the port-forward-scripts

**Comment by steeling** [comment]
@quan is taking dockerfile
@barghav is taking the helm chart
@heba is doing makefile
@sean is fixing up the port-forward scripts

go hello world is free to take

**Comment by bnookala** [comment]
Added the modification to the helm chart: https://github.com/steeling/osm/pull/12
