### ISSUE TITLE
Create e2e tests under tests/e2e

### ISSUE THREAD

**Issue by steeling** [steeling/osm#20]
The e2e tests will:

1. Call out to the K8s master with some egress policies that are both valid and invalid. We can use this library a) pkg/gen/client/policy/clientset/versioned/typed/policy/v1alpha1/policy_client.go

b) pkg/apis/policy/v1alpha1/egress.go is the type we can fill out to send to the K8s master.

We can assume that the validating webhook is running and that the k8s API forwards requests as needed

Need to grep through the code more, but we'll want to surface the policy_client in tests/framework/common.go

**Comment by cmgit** [comment]
port to expect is 9093
